{"tests": [{"data": {"status": "failure", "inputs": {"name1": "OE2", "segid2": "HET", "segid1": "PRO", "pdbin": {"src": "hda", "id": "5729865256bc2525"}, "resid1": "212", "resid2": "3", "name2": "C1", "dcdin": {"src": "hda", "id": "2891970512fa2d5a"}}, "output_problems": ["No JSON object could be decoded", "Job in error state."], "job": {"inputs": {"pdbin": {"src": "hda", "id": "5729865256bc2525", "uuid": "a07e5a93-d840-4a19-aad5-5ac891836180"}, "dcdin": {"src": "hda", "id": "2891970512fa2d5a", "uuid": "2b4f1e13-b797-4fd5-b9be-e0f673e03826"}}, "update_time": "2018-10-04T19:03:51.571267", "tool_id": "mda_distance_analysis", "outputs": {"output": {"src": "hda", "id": "54f2a3a23292eb07", "uuid": "adda9408-e87e-4179-a6aa-8b5f4c375a4c"}, "distance_plot": {"src": "hda", "id": "8155e4b4bf1581ff", "uuid": "c8925381-cdf5-4f54-a5d4-ab560074ebad"}}, "stdout": null, "command_line": "python '/home/ubuntu/Documents/galaxy-tools-compchem/tools/MDAnalysis/distance.py' --idcd '/tmp/tmpyuKrbH/files/000/dataset_1.dat' --ipdb '/tmp/tmpyuKrbH/files/000/dataset_2.dat' --isegid1 'PRO' --iresid1 '212' --iname1 'OE2' --isegid2 'HET' --iresid2 '3' --iname2 'C1' --output '/tmp/tmpyuKrbH/files/000/dataset_3.dat' --odistance_plot '/tmp/tmpyuKrbH/files/000/dataset_4.dat' 2>&1", "exit_code": null, "state": "queued", "create_time": "2018-10-04T19:03:46.348508", "params": {"name1": "\"OE2\"", "segid2": "\"HET\"", "segid1": "\"PRO\"", "dbkey": "\"hg17\"", "resid1": "\"212\"", "resid2": "\"3\"", "name2": "\"C1\"", "chromInfo": "\"/opt/galaxy/galaxy-app/tool-data/shared/ucsc/chrom/hg17.len\""}, "stderr": null, "job_metrics": [], "model_class": "Job", "external_id": null, "id": "54f2a3a23292eb07", "user_email": "test@bx.psu.edu"}, "problem_log": "  File \"/usr/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/opt/galaxy/galaxy-app/test/functional/test_toolbox.py\", line 299, in test_tool\n    self.do_it( td )\n  File \"/opt/galaxy/galaxy-app/test/functional/test_toolbox.py\", line 75, in do_it\n    raise e\nNo JSON object could be decoded\nJob in error state.\n-------------------- >> begin captured stdout << ---------------------\nHistory with id 2891970512fa2d5a in error - summary of datasets in error below.\n--------------------------------------\n| 3 - Distance Analysis raw data (HID - NAME) \n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  discarding /home/ubuntu/miniconda2/bin from PATH\n|  prepending /tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/bin to PATH\n|  Traceback (most recent call last):\n|  File \"/home/ubuntu/Documents/galaxy-tools-compchem/tools/MDAnalysis/distance.py\", line 6, in\n| Dataset Job Standard Output:\n|  discarding /home/ubuntu/miniconda2/bin from PATH\n|  prepending /tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/bin to PATH\n|  Traceback (most recent call last):\n|  File \"/home/ubuntu/Documents/galaxy-tools-compchem/tools/MDAnalysis/distance.py\", line 6, in <module>\n|  import MDAnalysis as mda\n|  File \"/tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/lib/python2.7/site-packages/MDAnalysis/__init__.py\", line 183, in <module>\n|  from .lib import log\n|  File \"/tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/lib/python2.7/site-packages/MDAnalysis/lib/__init__.py\", line 36, in <module>\n|  from . import util\n|  File \"/tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/lib/python2.7/site-packages/MDAnalysis/lib/util.py\", line 174, in <module>\n|  import mmtf\n|  ImportError: No module named mmtf\n|  discarding /home/ubuntu/miniconda2/bin from PATH\n|  prepending /tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/bin to PATH\n| Dataset Job Standard Error:\n|  Fatal error: Exit code 1 ()\n|  Traceback (most recent call last):\n|  File \"/tmp/tmpyuKrbH/job_working_directory/000/3/set_metadata_edkoQX.py\", line 1, in <module>\n|  from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()\n|  File \"/opt/galaxy/galaxy-app/lib/galaxy_ext/metadata/set_metadata.py\", line 23, in <module>\n|  from sqlalchemy.orm import clear_mappers\n|  ImportError: No module named sqlalchemy.orm\n|\n--------------------------------------\n| 4 - Distance Analysis Plot (HID - NAME) \n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  discarding /home/ubuntu/miniconda2/bin from PATH\n|  prepending /tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/bin to PATH\n|  Traceback (most recent call last):\n|  File \"/home/ubuntu/Documents/galaxy-tools-compchem/tools/MDAnalysis/distance.py\", line 6, in\n| Dataset Job Standard Output:\n|  discarding /home/ubuntu/miniconda2/bin from PATH\n|  prepending /tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/bin to PATH\n|  Traceback (most recent call last):\n|  File \"/home/ubuntu/Documents/galaxy-tools-compchem/tools/MDAnalysis/distance.py\", line 6, in <module>\n|  import MDAnalysis as mda\n|  File \"/tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/lib/python2.7/site-packages/MDAnalysis/__init__.py\", line 183, in <module>\n|  from .lib import log\n|  File \"/tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/lib/python2.7/site-packages/MDAnalysis/lib/__init__.py\", line 36, in <module>\n|  from . import util\n|  File \"/tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/lib/python2.7/site-packages/MDAnalysis/lib/util.py\", line 174, in <module>\n|  import mmtf\n|  ImportError: No module named mmtf\n|  discarding /home/ubuntu/miniconda2/bin from PATH\n|  prepending /tmp/tmpyuKrbH/job_working_directory/000/3/conda-env/bin to PATH\n| Dataset Job Standard Error:\n|  Fatal error: Exit code 1 ()\n|  Traceback (most recent call last):\n|  File \"/tmp/tmpyuKrbH/job_working_directory/000/3/set_metadata_edkoQX.py\", line 1, in <module>\n|  from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()\n|  File \"/opt/galaxy/galaxy-app/lib/galaxy_ext/metadata/set_metadata.py\", line 23, in <module>\n|  from sqlalchemy.orm import clear_mappers\n|  ImportError: No module named sqlalchemy.orm\n|\n--------------------------------------\n\n--------------------- >> end captured stdout << ----------------------", "problem_type": "functional.test_toolbox.JobOutputsError"}, "id": "functional.test_toolbox.TestForTool_mda_distance_analysis.test_tool_000000", "has_data": true}], "version": "0.1", "exit_code": 1, "summary": {"num_skips": 0, "num_errors": 0, "num_failures": 1, "num_tests": 1}}